CREATE TABLE HIVE_QUERY(
   DATASET_NAME       TEXT    NOT NULL,
   QUERY              TEXT    NOT NULL,
   COUNT_COLUMN       TEXT    NOT NULL,
   MIN_VAL            INT     NOT NULL,
   MAX_VAL            INT     NOT NULL
);

CREATE TABLE EXECUTION_RESULT(
   DATASET_NAME       TEXT    NOT NULL,
   EXECUTION_TS       TIMESTAMP NOT NULL,
   VALUE              INT     NOT NULL
);
